---
title: Test Post 1
author: Yusuf Mian
date: '2022-09-09'
slug: []
categories: []
tags: []
---


```{r, include=TRUE, message=FALSE, warning=FALSE, echo=FALSE, eval=TRUE, fig.align="center"}
library(ggplot2)
library(tidyverse)
#### want a state-level analysis
library(readr)
setwd("~/Desktop/Election Analysis/Election-Blog")
popvote_df <- read_csv("house nationwide vote and seat share by party 1948-2020.csv")
house_party_vote_share_by_district_1948_2020 <- read_csv("house party vote share by district 1948-2020.csv")
h <- house_party_vote_share_by_district_1948_2020
```

# Interactive Session in \texttt{R Studio}

## Geographic and temporal trends in midterm elections?

```{r, include=TRUE, message=FALSE, warning=FALSE, echo=TRUE, eval=TRUE, fig.align="center"}
## make map of vote share by state and CD

# start with 114th congress - 2014 election
# required packages 
require(tidyverse)
require(ggplot2)
require(sf)

# load geographic data
get_congress_map <- function(cong=117) {
  tmp_file <- tempfile()
  tmp_dir  <- tempdir()
  zp <- sprintf("https://cdmaps.polisci.ucla.edu/shp/districts114.zip",cong)
  download.file(zp, tmp_file)
  unzip(zipfile = tmp_file, exdir = tmp_dir)
  fpath <- paste(tmp_dir, sprintf("districtShapes/districts114.shp",cong), sep = "/")
  st_read(fpath)
}

# load 114th congress
cd117 <- get_congress_map(117)

# select specific state 
cd117_mi <- cd117 %>% 
            filter(STATENAME=="Michigan") %>%
            mutate(DISTRICT = as.character(DISTRICT))%>%
            select(DISTRICT)

# add data to plot - 2014 GOP party seat share
# reload election data - h from previous exercise
h <- house_party_vote_share_by_district_1948_2020

# filter for 2014 election and state
R_mi_2020 <- h %>%
    filter(raceYear == 2020, State == "Michigan") %>%
    select(raceYear, State, district_num, RepVotesMajorPercent, DemVotesMajorPercent) %>%
  # summarize party vote share by district
    group_by(district_num) %>%
    summarise(Rep_votes_pct = RepVotesMajorPercent) %>%
  # rename district variable name to match shapefile
    rename(DISTRICT = district_num)

# before joining dfs, check classes of variable to be merged on
class(R_mi_2020$DISTRICT)
class(cd117_mi$DISTRICT)

# change class
cd117_mi$DISTRICT <- as.numeric(cd117_mi$DISTRICT)

# join election returns with shapefiles
cd117_mi <- cd117_mi %>% left_join(R_mi_2020, by="DISTRICT")
cd117_mi

# time to map!
ggplot() + 
  geom_sf(data=cd117_mi,aes(fill=Rep_votes_pct),
          inherit.aes=FALSE,alpha=0.9) + 
  scale_fill_gradient(low = "white", high = "black", limits=c(10,80)) +
  theme_void() + ggtitle ("Republican Vote Share in 2020 MI Congressional Elections")
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) 

## make map of GOP vote share by state (national) - 2014
# use h dataset from earlier
# house_party_vote_share_by_district_1948_2020 <- 
  # read_csv("house party vote share by district 1948-2020.csv")
# h <- house_party_vote_share_by_district_1948_2020
 
# filter for relevant variables
R_2020 <- h %>%
    filter(raceYear == 2020) %>%
    select(raceYear, State, district_num, district_id, RepVotes, DemVotes) %>%
  # summarize party vote share by state
    group_by(State) %>%
  # mutate Rep vote margin by state %>%
    mutate(R_votemargin_st = (sum(RepVotes))/
                            sum(RepVotes + DemVotes),
           D_votemargin_st = (sum(DemVotes))/
                            sum(RepVotes + DemVotes)) %>%
    rename(state = State)

# load usmap
# install.packages('plot_usmap')
library(usmap)

states_map <- usmap::us_map()
unique(states_map$abbr)

# plot
plot_usmap(data = R_2020, regions = "states", labels=TRUE, values = "R_votemargin_st") + 
  scale_fill_gradient(low = "white", high = "red", name = "GOP two-party voteshare margin") +
  theme_void() +labs(title="Republican Popular Vote Share in 2020 US House Elections")

```